### PR TITLE
Fix: app.js MouseClick Event

### PR DESCRIPTION
**Pull request by SebSeifert**
Deutsch:
Beim Mausklick haben sich die Graphen in Firefox nicht geöffnet. Durch die Anpassung funktioniert das jetzt auch in Firefox.

Englisch:
On Mouseclick the Graphs didn't show in Firefox. Now it's working in Firefox too.

### CODE REVIEW

**Comment by SebSeifert** [comment]
Deutsch:
Da ich SSL via LetsEncrypt nutze ändern sich ständig die SHA1 Fingerprint. Deshalb nutze ich ein simples PHP Script um diesen bei jedem Senden abzufragen. Die verbindung dorthin sollte http sein (bei mir ein lokaler RPi.

Englisch:
Because i'm using SLL with LetsEncrypt the SHA1 Fingerprint change every 90 days. For this i have an simple PHP Script that delivers me this Fingerprint on every send of the Sensor. Connection to the Script should be local http (for me an local RPi).

**Comment by flazer** [comment]
Hey Seb.
I've added a new sketch, which is checking against the root CA. Please give it a try. I think it's a much cleaner and more secure way then requesting the fingerprint via http.

**Comment by SebSeifert** [comment]
Yeah thank you for that! But i'm not Sure if the LetsEncrypt CA stays always the same. But anyway I changed to an HTTP via VPN solution and the /save API is only via an VPN reachable because of Security. At home i have an RPi VPN Gateway that Acts as Client and static Routes in my Fritzbox to route all Traffic to this IPs through my RPi VPN Gateway.
Feel free to ask for more details 😆 
I know it's a little bit complicated but i wanted to have an public frontend site but no Trolls that are feeding my Database with crap.
Please feel free to make my Code better for the Security that only VPN IPs can reach it. I had to set an static IP for my VPN Client and i dont know how to get Variables from the .env File :/
Here are my changes on /web/app/Http/Controllers/ApiController.php

 ```
  public function save(Request $request) {
        $errors = [];

	if (getenv('REMOTE_ADDR') != 'VPN IP ADDRESS')
  	abort(403);

        $data = $request->all();
        if (isset($data['token'])) $data['token'] = md5($data['token']);
        $validation = Validator::make($data, [
            'token' => 'required|string|min:2|max:60|exists:devices,token'
        ]);

```

And please think for the app.js MouseClick Event. That's a bug not a feature. The i can say i've contributed and not totally dumb 🤣

**Comment by SebSeifert** [comment]
Or i open an new Pull request and cancel this one.

**Pull request closed without merging**
